export const queryKeys = {
  billing: (type?: string) => ['platform', 'billing', type] as const,
  tenants: (filters?: Record<string, unknown>) => ['tenants', filters] as const,
  users: (filters?: Record<string, unknown>) => ['users', filters] as const,
  auditLogs: (filters?: Record<string, unknown>) => ['auditLogs', filters] as const,
  teacherDashboard: (name: string) => ['teacher', 'dashboard', name] as const,
  studentDashboard: (email?: string) => ['student', 'dashboard', email] as const,
  parentDashboard: (name: string) => ['parent', 'dashboard', name] as const,
  tenantDetail: (id: string) => ['tenant', 'detail', id] as const,
  subjects: ['subjects'] as const,
  classes: ['classes'] as const,
  teachers: ['teachers'] as const,
  students: ['students'] as const,
  parents: ['parents'] as const,
  notices: ['notices'] as const,
  fees: ['fees'] as const,
  attendance: ['attendance'] as const,
  staff: ['staff'] as const,
  subscriptions: ['subscriptions'] as const,
}
