"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _full_app_shell from './full-app-shell.bones.json'

registerBones({
  "full-app-shell": _full_app_shell,
})
